---

- name: apt | vortessence dependencies install
  apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - mysql-server
    - python-mysqldb
    - python-pip
    - supervisor

- set_fact:
    supervisor_confdir: /etc/supervisor/conf.d
    supervisor_ext: conf
    supervisor_service: supervisor
