---

- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: redhat.yml
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: ramdisk.yml
- include: vortessence.yml

- name: set supervisor config to manage vortessence runserver
  template: src=supervisor-vortessence-server.ini dest={{ supervisor_confdir }}/vortessence-runserver.{{ supervisor_ext }} mode=0644
  notify:
    - restart supervisor


