---

- name: Redhat | Install vortessence dependencies
  yum:
    name:
      - git
      - mariadb
      - mariadb-server
      - MySQL-python
      - python-pip
      - python-devel
      - supervisor
      - gcc
    state: present
    update_cache: yes
  register: pkg_result
  until: pkg_result is success
