---

- name: Redhat | Install vortessence dependencies
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - git
    - mariadb
    - mariadb-server
    - MySQL-python
    - python-pip
    - supervisor
    - gcc

- name: Redhat | Ensure Mysql/Mariadb is running and enabled on boot.
  service: name=mariadb state=started enabled=yes
- name: Redhat | Ensure Supervisord is running and enabled on boot.
  service: name=mariadb state=started enabled=yes

- set_fact:
    supervisor_confdir: /etc/supervisord.d
    supervisor_ext: ini
    supervisor_service: supervisord

