---

- name: Redhat | Install vortessence dependencies
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - git
    - mariadb
    - mariadb-server
    - MySQL-python
    - python-pip
    - python-devel
    - supervisor
    - gcc

